name: deploy_dev1
on: 
workflow_dispatch:
		inputs:
			job_nme:
			type: choice
			description: 'Select Job name'
			required : True
			options:
				- job1
				- job2
				- job3
jobs:
	job1:
    	runs-on: ubuntu-latest
    	steps:
        - name: my-step
        run: echo "Hello Github Actions! - job1"
	  
   	job2:
    	runs-on: ubuntu-latest
    	steps:
      	- name: my-step
        run: echo "Hello Github Actions!- job2 "
